# Generated by Django 2.1.1 on 2018-09-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingtip',
            name='odds',
            field=models.FloatField(default=1.5),
            preserve_default=False,
        ),
    ]
